version: "3"

volumes:
  goa-mysql-volume:

services:
  goa-server:
    container_name: goa-server
    build:
      context: .
      dockerfile: ./docker/goa-server/Dockerfile
    ports:
      - "8088:8088"
    tty: true
    restart: always
    volumes:
      - .:/app
    depends_on:
      - go-mysql

  go-mysql:
    image: mysql:8.0.21
    container_name: go-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'go_mysql8_development'
    # MySQLの文字コードを指定する
    volumes:
      # DBデータの永続化
      - goa-mysql-volume:/var/lib/mysql
      # MySQL起動時にDBを作成し、初期データの投入する
      - "./Docker/mysql/sql:/docker-entrypoint-initdb.d"
      - "./Docker/mysql/my.cnf:/etc/mysql/conf.d/etc-mysql.cnf"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./gen/http/openapi3.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

  go-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: go-phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=go-mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - go-mysql
    ports:
      - 9000:80

  go-smtp:
    image: schickling/mailcatcher
    container_name: go-smtp
    ports:
     - "1080:1080"
     - "1025:1025"