version: "3"

volumes:
  goa-mysql-volume:

services:
  goa-server:
    container_name: goa-server
    build:
      context: .
      dockerfile: ./docker/goa-server/Dockerfile
    ports:
      - "8088:8088"
    tty: true
    restart: always
    depends_on:
      - go-mysql

  go-mysql:
    container_name: go-mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      # gorm can struct->automigrate as well
      - ./mysql/init:/docker-entrypoint-initdb.d
      - goa-mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./gen/http/openapi3.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

  go-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: go-phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=go-mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - go-mysql
    ports:
      - 9000:80

  go-smtp:
    image: schickling/mailcatcher
    container_name: go-smtp
    ports:
     - "1080:1080"
     - "1025:1025"